<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>

   <ItemGroup>
    <ProjectReference Include="..\MechanicShop.Tests.Common\MechanicShop.Tests.Common.csproj" />
    <ProjectReference Include="..\..\src\MechanicShop.Api\MechanicShop.Api.csproj" />
  </ItemGroup>

</Project>
